from .population_sector import PopulationSector, PopulationParams, CANADA_POPULATION_PARAMS, NIGERIA_POPULATION_PARAMS
from .capital_sector import CapitalSector, CapitalParams, CANADA_CAPITAL_PARAMS, NIGERIA_CAPITAL_PARAMS
from .agriculture_sector import AgricultureSector, AgricultureParams, CANADA_AGRICULTURE_PARAMS, NIGERIA_AGRICULTURE_PARAMS
from .pollution_sector import PollutionSector, PollutionParams, CANADA_POLLUTION_PARAMS, NIGERIA_POLLUTION_PARAMS
from .nutrition_sector import NutritionSector, NutritionParams, CANADA_NUTRITION_PARAMS, NIGERIA_NUTRITION_PARAMS
